---
# Connection defaults for the 16 Cisco IOS devices in the GNS3 Fabric
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios

# Centralized Syslog Collector Target (from Day 18 logs)
syslog_server_ip: 192.168.122.1
syslog_udp_port: 10514
syslog_trap_level: 5          # Level 5 and above (Notifications, Warnings, Errors...)

# Out-of-Band Management VLAN Definition (from Day 11 logs)
management_vlan_id: 99
management_vlan_name: "managementVLAN"
management_vlan_gateway: 10.1.99.1
